apiVersion: v2
name: authenticated-rpc-tezos-chain
description: A Helm chart for Tezos RPC authentication for a private chain
type: application
version: 0.0.0
keywords:
  - tezos
  - blockchain
home: https://github.com/tqtezos/tezos-k8s
