apiVersion: v2
name: tezos-chain
description: A Helm chart for Tezos nodes on Kubernetes
type: application
version: 0.0.0
keywords:
  - tezos
  - blockchain
home: https://github.com/tqtezos/tezos-k8s
