{{- if (include "tezos.shouldDeployNomadicIndexer" .) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.nomadic_indexer_statefulset.name }}
  namespace: {{ .Release.Namespace }}
spec:
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.nomadic_indexer_statefulset.name }}
  serviceName: ""
  template:
    metadata:
      labels:
        app: {{ .Values.nomadic_indexer_statefulset.name }}
    spec:
      initContainers:
        - image: registry.gitlab.com/nomadic-labs/tezos-indexer/tezos-indexer:v9.1.0
          command: ["/bin/bash","-c"]
          args: [ "/home/tezos/tezos-indexer --db-schema | tee /docker-entrypoint-initdb.d/tezos-indexer-schema.sql" ]
          name: schema-extractor
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/
              name: schema-volume
      containers:
        - image: registry.gitlab.com/nomadic-labs/tezos-indexer/tezos-indexer:v9.1.0
          name: tezos-indexer
          args:
            - --debug
            - --verbosity=1
            - --no-contract-balances
            - --db=postgresql://localhost/tezos
            -  --tezos-url={{ .Values.indexer.rpc_url }}
        - image: postgres:alpine
          name: postgres
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/
              name: schema-volume
            - mountPath: /var/lib/postgresql/data
              name: indexer-db
          envFrom:
          - configMapRef:
              name: db-creds
      volumes:
        - emptyDir: {}
          name: schema-volume
  volumeClaimTemplates:
    - metadata:
        name: indexer-db
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "5Gi"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-creds
data:
  POSTGRES_USER: tezos
  POSTGRES_PASSWORD: tezosrocks
  POSTGRES_DB: tezos
{{- end }}
