apiVersion: v1
kind: Service
metadata:
  name: tezos-node-rpc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 8732
      name: rpc
  selector:
    appType: tezos-node
  type: NodePort
---
{{- if (include "tezos.shouldDeployRegularNodeStatefulset" .) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.regular_node_statefulset.name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.regular_node_statefulset.name }}
{{- end }}

{{- if (include "tezos.shouldDeployBakerStatefulset" .) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.baker_statefulset.name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.baker_statefulset.name }}
{{- end }}
---
{{- if (include "tezos.shouldDeployBcdIndexer" .) }}
apiVersion: v1
kind: Service
metadata:
  name: bcd
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 14000
      name: bcd
  selector:
    app: {{ .Values.bcd_indexer_statefulset.name }}
  type: NodePort
{{- end }}
