{{ define "snapshot-scheduler.name" }}
{{- $history_mode := $.history_mode }}
  {{- printf "%s-%s-%s" "snapshot-scheduler-for" $history_mode "node" }}
{{- end }}

{{- range $node, $config := .Values.nodes }}
{{- if $config }}
  {{- $_ := set $ "history_mode" $config.history_mode }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snapshot-scheduler.name" $ }}
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "snapshot-scheduler.name" $ }}
  template:
    metadata:
      labels:
        app: {{ include "snapshot-scheduler.name" $ }}
    spec:
      serviceAccountName: {{ $.Values.service_account }}
      containers:
        - name: {{ include "snapshot-scheduler.name" $ }}
          image: {{ index $.Values.tezos_k8s_images "snapshot-engine"}}
          imagePullPolicy: Always
          args:
              - "snapshot-scheduler"
          env:
            - name: HISTORY_MODE
              value: {{ $config.history_mode }}
            - name: NAMESPACE
              value: {{ $.Release.Namespace }}
            - name: IMAGE_NAME
              valueFrom:
                configMapKeyRef:
                  name: snapshot-configmap
                  key: IMAGE_NAME
---
{{- end }}
{{- end }}