apiVersion: v1
data:
  NAMESPACE: {{ $.Release.Namespace }}
  IMAGE_NAME: {{ $.Values.tezos_k8s_images.snapshotEngine }}
  TEZOS_IMAGE: {{ $.Values.images.octez }}
  SNAPSHOT_MARKDOWN_TEMPLATE_URL: {{ $.Values.snapshotMarkdownTemplateUrl }}
  SERVICE_ACCOUNT: {{ $.Values.service_account }}
  RESTORED_STORAGE_INIT_TIME: {{ $.Values.restoredStorageInitTime }}
kind: ConfigMap
metadata:
  name: snapshot-configmap
  namespace: {{ $.Release.Namespace }}