apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "tezos-reward-distributor.fullname" . }}
  labels:
    {{- include "tezos-reward-distributor.labels" . | nindent 4 }}
spec:

  # important to prevent launch of concurrent payout processes
  concurrencyPolicy: Forbid

  failedJobsHistoryLimit: 100
  schedule: {{ .Values.schedule }}
  jobTemplate:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tezos-reward-distributor.selectorLabels" . | nindent 8 }}
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 1000
          volumes:
            - name: storage
              persistentVolumeClaim:
                claimName: {{ include "tezos-reward-distributor.fullname" . }}-volume
            - name: config-volume
              configMap:
                name: {{ include "tezos-reward-distributor.fullname" . }}-config
            - name: secret-volume
              secret:
                secretName: {{ include "tezos-reward-distributor.fullname" . }}-secret
          initContainers:
            # Work around a bug where fsGroup is ignored
            - name: change-ownership-container
              image: {{ .Values.images.tezos_reward_distributor }}
              command:
              - /bin/sh
              - -c
              - "mkdir -p /trd/cfg && chown -R 1000:1000 /trd"
              securityContext:
                runAsUser: 0
                privileged: true
              volumeMounts:
              - mountPath: /trd
                name: storage
            - name: tezos-reward-distributor-cron-job
              image: {{ .Values.images.tezos_reward_distributor }}
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - mountPath: /trd
                  name: storage
                - mountPath: /trd/cfg/config.yaml
                  name: config-volume
                  subPath: config.yaml
              command:
              - /bin/sh
              args:
              - "-c"
              - |
{{ tpl ($.Files.Get (print "scripts/run.sh")) $ | indent 16 }}
              env:
              - name: REWARD_DATA_PROVIDER
                value: "{{ .Values.reward_data_provider }}"
              - name: TEZOS_NODE_ADDR
                value: "{{ .Values.tezos_node_addr }}"
              - name: SIGNER_ADDR
                value: "{{ .Values.signer_addr }}"
              - name: EXTRA_TRD_ARGS
                value: "{{ .Values.extra_trd_args }}"
              - name: NETWORK
                value: "{{ .Values.network }}"
              - name: ADJUSTED_EARLY_PAYOUTS
                value: "{{ .Values.adjusted_early_payouts }}"
              - name: INITIAL_CYCLE
                value: "{{ .Values.initial_cycle }}"
              - name: DRY_RUN
                value: "{{ .Values.dry_run }}"
          containers:
            - name: report-uploader
              image: {{ .Values.tezos_k8s_images.snapshotEngine }}
              volumeMounts:
              - mountPath: /trd
                name: storage
              - mountPath: /trd/cfg/bucket_upload_secrets
                name: secret-volume
                subPath: bucket_upload_secrets
              command:
              - /bin/sh
              args:
              - "-c"
              - |
{{ tpl ($.Files.Get (print "scripts/bucket_upload.sh")) $ | indent 16 }}
              env:
              - name: BUCKET_ENDPOINT_URL
                value: "{{ .Values.bucket_upload.bucket_endpoint_url }}"
              - name: BUCKET_NAME
                value: "{{ .Values.bucket_upload.bucket_name }}"
              - name: BAKER_NAME
                value: {{ include "tezos-reward-distributor.fullname" . }}
          restartPolicy: OnFailure
